version: "3.3"
services:
  api:
    image: marsksenior/my-project:financial-report-be
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
      args:
        - HEADER_FILE=header_production.go
        - ENV_FILE=.env
    restart: unless-stopped
    depends_on:
      - redis-prd
    ports:
      - 12002:12002
    networks:
      - api-net
    extra_hosts:
    - "host.docker.internal:host-gateway"

  redis-prd:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - api-net
    ports:
      - 6379:6379

networks:
  api-net:
   driver: bridge
